version: '2'

services:
  zookeeper:
    build:
      context: .
      args: 
        - CLIENTPORT=2182
    environment:
      - MYID=1
      - SERVERS=localhost,localhost,localhost
      - CLIENTPORT=2182
    network_mode: "host"
    restart: always
    image: crossz/zookeeper-cluster-distributed
